### ISSUE TITLE
2.0.0-beta1: Inserttag not correctly 

### ISSUE THREAD

**Issue by reluem** [contao-bootstrap/layout#6]
The bootstrap layout in Contao 4.4 seems to break the {{ua::class}} inserttag.
When using app_dev.php, everything is fine
`<body id="top" class="mac safari webkit sf11" itemscope="" itemtype="http://schema.org/WebPage">`
but in the regular app.php the body tags look like this.
`<body id="top" class="<esi:include src=" onerror="continue">`

If I use the standard Contao page layout, everything works fine. Same if I manually delete the {{ua::class}} from fe_bootstrap.html5

Any ideas why this could be happening?

**Comment by dmolineus** [comment]
Where do you add the `{{ua::class}}` inserttag? In the page layout or directly in the template?

**Comment by reluem** [comment]
it’s in the body tag of fe_bootstrap.html5 by default, so directly in the template.

**Comment by dmolineus** [comment]
Stupid question. It's always in the template I noticed after I sent the comment.

I can't reproduce this issue. It work's with Contao 4.4.8 in my installation. It's probably caused by the `ReplaceCssClassesFilter` listener. Contao 4 creates esi tags for the insert tags which breaks the html markup.

Could you provide the steps how to reproduce it (Special settings like caching and so on)?

**Comment by reluem** [comment]
Okay, in a clean installation using demo data by [bytehead/contao-4-demo](http://github.com/bytehead/contao-4-demo) and the Bootstrap Bundle, everything works fine.

I then tried to reinstall my dependencies, and figured out that in fact [heimrichhannot/contao-hyphenator](https://github.com/heimrichhannot/contao-hyphenator) causes the problem. 

Since the hyphenator is not working anyways in Contao 4.4, the issue here can be closed!
Thanks!

**Comment by dmolineus** [comment]
Thanks for pointing this out.
